language: node_js
node_js:
- 12.8.3
cache: yarn


install:
  - yarn ci

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages